apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels:
    app:  myapp-service
spec:
  selector:
    app: vinay1
  type: Loadbalance
  ports:
    - nodePort: 30000
      port: 8080
      targetPort: 8080
